server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password:
# kiểm tra ngay trên hệ thống luôn nêú size vượt quá chưa cần đến kiểm tra trên code
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1

